# mad lib "Be Kind" game.
''' In this game user is asked to enter any noun, adjectives, plural noun or any other words called mad lib and then rearranged to make different sentences.'''
Noun_1 = input('Enter any noun')
pluralNoun = input('Enter pluralnoun')
Noun_2 = input('enter any noun')
place = input ('Enter any place name')
Adjective = input('Enter any adjective')
Noun_3 = input ('Enter any Noun')

print('Be kind to your',Noun_1, '-footed',pluralNoun)
print("For duck may be somebody's",Noun_2)
print("Be kind to your", pluralNoun, "in",place)
print('Where the weather is always', Adjective)
print("You may think that this is the", Noun_3)
print('Well it is.')



# number guessing name
""" In this game user guesses the random number generated by the computer. 
The range of the lower and upper bound will decide the number of guesses user can have."""

import random
import math

# Input
lowest_value = int(input("enter lowest value:- "))
upper_value = int(input("enter upper value:- "))

# random number generation
x = random.randint(lowest_value, upper_value)

# number of guesses
print("\n You've only", round(math.log(upper_value - lowest_value +1, 2)),"chances to guess the integer.")

# initialize the guess
count = 0

while count < math.log(upper_value - lowest_value + 1, 2):
    count += 1
    guess = int(input("Guess the number:- "))
    
    
    if (x == guess):
        print("Congratulations you did it in", count, "try")
    elif (x > guess):
        print("You guess lower number:-")
    elif (x < guess):
        print("You guessed higher number")

if count >= math.log(upper_value - lowest_value +1, 2):
    print("The number is %d"%x)
    print("Better luck next time") 


